### ISSUE TITLE
Front-end user menus items for subsites

### ISSUE THREAD

**Issue by pbrocks** [strangerstudios/pmpro-network-subsite#11]
Nevertheless the issue that prompted this ticket doesn’t appear to be resolved – to duplicate the front-end user menus as they’re running on the main site, I need to be able to add a unique display location for each membership level under Menu Settings in the Menu Editor on sub-sites, as I currently can on the main site.
[Main Site Menus](https://www.aferm.co/wp-content/uploads/2018/01/MenuMain.jpg)
<img src="https://www.aferm.co/wp-content/uploads/2018/01/MenuMain.jpg" />
vs
[Subsite Menus](https://www.aferm.co/wp-content/uploads/2018/01/MenuSub.jpg)
<img src="https://www.aferm.co/wp-content/uploads/2018/01/MenuSub.jpg" />

**Comment by andrewlimaza** [comment]
The Nav Menu Add On works with this plugin, you need to recreate the menu on eeach subsite for members, logged-in non-members etc.
