### ISSUE TITLE
Lock down posts per category

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-network-subsite#15]
We should look into locking down post categories per membership level on a subsite.

**Comment by coneos** [comment]
Amazing plugin thank you!

I just have also this issue with Multisite membership, it does work for subsites when I assign the main site membership in the post but it doesn’t work with categories.

I followed your tutorial below, created one category on main site then the exact same one changing the same id in wp_X_terms and wp_X_term_taxonomy.
Then I activated the add on, synchronize with main site but it is not asking for a membership when I assign that category on the subsite

https://www.paidmembershipspro.com/network-multisite-mega-post-paid-memberships-pro/#3

My goal is to let members assign a category to their post so their subscribers can have access. I don’t want to give them the ability to choose another membership.
Do you have a snippet that could do that? They don’t even have to select a category, I guess I could just add a membership X automatically to each post of author Y when it gets published?

THanks!

**Comment by andrewlimaza** [comment]
This is quite difficult to achieve, due to that category ID's won't always match the main site. While it may be possible if you ensure both category ID's are the same across multiple sites it _might_ work.

I recommend using the pmpro_has_membership_access_filter to have a custom code snippet for categories and restrictions on subsites. We are looking into a better way to achieve this.

**Comment by andrewlimaza** [comment]
Update: This is now supported through the "category" edit functionality that allows you to assign membership levels to the categories when editing the post category.

I like this as it still gives you flexibility to restrict different categories to the same membership level and variations.

![Screenshot 2023-12-11 at 15 18 28](https://github.com/strangerstudios/pmpro-network-subsite/assets/12629136/6301d5fd-f48c-4af5-9250-ebfe9bf1b6f1)
