### ISSUE TITLE
Expand subsite core functionality

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-network-subsite#16]
Some functions available in PMPro core could be helpful to expand to be available in the subsite. For example, the global variable `$pmpro_pages` or the function `pmpro_url()` to allow redirecting a user from the subsite to specific PMPro pages on the primary network site. 

Example:

https://gist.github.com/ipokkel/2d22e1bc0dcc949db5ac171d4e147f02

**Comment by andrewlimaza** [comment]
This is done! :)
