### ISSUE TITLE
Detailed information?

### ISSUE THREAD

**Issue by mentolnet** [strangerstudios/pmpro-network-subsite#2]
Hello. I cannot understand exactly what this code achieves and how. I am guessing that, once installed on a subsite of the network, it will contact the network´s main site to check if the user has privileges to access the subsite? A valid membership, etc?
Could you please explain in more detail how to setup this properly? I´ve followed the instructions over at http://www.paidmembershipspro.com/add-ons/plugins-on-github/pmpro-network-membership/ but i cannot actually see any difference after the addon is installed.
Thank you.

**Comment by fabiobfava** [comment]
Hi Jason & Kim! I have one doubt:

 When you say to "Make sure that the constant PMPRO_NETWORK_MAIN_DB_PREFIX is properly defined for your main network site in your wp-config.php file", you mean I should add the line to my wp-config.php file?

define('PMPRO_NETWORK_MAIN_DB_PREFIX', 'wp');

Finally, at the end of this line, should I keep 'wp' or change to 'my_db_prefix_' instead? This is not very clear on the Add-On page and I want to implement this on my site (have forums, courses, woocommerce store, on subsites, so I can leverage the whole multisite).

Would you mind to clear that before I can proceed?

Thank you very much and best regards (your software is awesome)!

**Comment by ideadude** [comment]
@fabiobfava on this line of your wp-config.php file you'll have your db prefix defined:
https://github.com/WordPress/WordPress/blob/master/wp-config-sample.php#L66

The main DB prefix is usually the same as this (although confusingly, our variable excludes the _ and the WP one includes it). So if your wp-config.php file says "wp_", then you should keep our constant defined as "wp".

That should work. As an added confusion, the "main" site on a network setup usually has the base DB prefix (wp_), but might have been changed to another subsite on the network which has a number in the prefix... so something like (wp_2_ or wp_3_, etc).

**Comment by ideadude** [comment]
We've updated our docs over here:
https://www.paidmembershipspro.com/add-ons/pmpro-network-membership/

I'm going to close this issue, but if someone has a specific question still. Feel free to ask. We are trying to improve the documentation and plugin to make this all easier to understand. It's confusing, even for us.
