### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Grace-n-Ease** [strangerstudios/pmpro-network-subsite#3]
The following doesn't seem to do anything anymore:

//remove admin pages
    remove_action('admin_menu', 'pmpro_add_pages');
    remove_action('admin_bar_menu', 'pmpro_admin_bar_menu');

The instructions on the plugin page are fairly cryptic. Is there any further instructions?

I'm using the latest version of PMPro and WP 4.2.2

Thanks

**Comment by Grace-n-Ease** [comment]
I recalled asking about this a year or so ago. I went back to the WP Support pages and found the following. The priority hadn't been set in the code. I thought by now it would have been added. Maybe you would add it so that this issue can be resolved?

remove_action('admin_bar_menu', 'pmpro_admin_bar_menu', 1000);

Thanks

**Comment by ideadude** [comment]
Thanks. Fixed in a pull request same as Grace n Ease did. It will go out in the next update.
