### ISSUE TITLE
Subsite fatal error if PMPro not activated on subsite before Multisite Memberships

### ISSUE THREAD

**Issue by wasanajones** [strangerstudios/pmpro-network-subsite#36]
Subsite dashboard throws a fatal error if PMPro not activated on subsite with Multisite Memberships

if you deactivate PMPro it generates this error --  (you have to delete the plugin file to regain access to dashboard)

Fatal error: Uncaught Error: Call to undefined function pmpro_get_crons()
in /home/spicypress/domains/xxx.com/public_html/wp-content/plugins/pmpro-network-subsite/pmpro-network-subsite.php on line 222

Call stack:

pmpro_multisite_remove_crons()
wp-includes/class-wp-hook.php:324
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:348
WP_Hook::do_action()
wp-includes/plugin.php:517
do_action()
wp-admin/admin.php:175
require_once()
wp-admin/plugins.php:10

**Comment by kimcoleman** [comment]
this is completed in #35
