### ISSUE TITLE
Correct Syntax Error

### ISSUE THREAD

**Issue by wpalways1** [strangerstudios/pmpro-network-subsite#7]
Hi there,

With assistance from @EkoJr we discoverer a syntax error on line 55 of `pmpro-network-subsite.php` 
 - single quotes were used instead of double quotes. Before fixing the syntax, membership levels were not flowing from the main site to the subsite. But this change corrected the issue:

Change line 55 in `pmpro-network-subsite.php` FROM

`$membership_levels = $wpdb->get_results( 'SELECT * FROM {$wpdb->pmpro_membership_levels}', OBJECT );`
TO
`$membership_levels = $wpdb->get_results( "SELECT * FROM {$wpdb->pmpro_membership_levels}", OBJECT );`

Hope this helps! -Ryan

**Comment by ideadude** [comment]
Fixed in that pull request. Thanks!
